version: '2'
services:
    prova3-app:
        image: prova3
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://prova3-mysql:3306/prova3?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    prova3-mysql:
        extends:
            file: mysql.yml
            service: prova3-mysql
